[package]
name = "bdk_kyoto"
version = "0.1.0"
edition = "2021"

[dependencies.kyoto]
git = "https://github.com/rustaceanrob/kyoto"
rev = "872012ed33b2da689fd0aa59fc55af25a974ddec"

[dependencies.bdk_wallet]
version = "1.0.0-alpha.13"

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[[example]]
name = "signet"

[[example]]
name = "wallet"
